name: Continuous Integration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -g -Wall -Wextra -Werror -I/usr/include/lua5.4
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install liblua5.4-dev
      - name: Compile
        run: ./build.sh
